DROP TABLE DEALER IF EXISTS;

CREATE TABLE DEALER (
  ID INTEGER generated by default as identity (start with 1) not null,
  NAME VARCHAR(45) NOT NULL,
  EMAIL VARCHAR(45) NOT NULL,
  ADDRESS VARCHAR(60) NOT NULL,
  LNG DECIMAL(8,6) NOT NULL,
  LAT DECIMAL(8,6) NOT NULL,
  PRIMARY KEY (ID));

INSERT INTO DEALER(ID,NAME,EMAIL,ADDRESS,LNG,LAT) VALUES(1,'Toyota Økern','post.okern@toyota.no','Kabelgaten 6, 0580 Oslo',10.815783,59.927173);
INSERT INTO DEALER(ID,NAME,EMAIL,ADDRESS,LNG,LAT) VALUES(2,'Toyota Oppsal','post.oppsal@toyota.no','Østmarkveien 25, 0687 Oslo',10.851274,59.892242);
INSERT INTO DEALER(ID,NAME,EMAIL,ADDRESS,LNG,LAT) VALUES(3,'Toyota Skøyen','post.skoyen@toyota.no','Drammensveien 161, 0277 Oslo',10.676115,59.922356);
INSERT INTO DEALER(ID,NAME,EMAIL,ADDRESS,LNG,LAT) VALUES(4,'Toyota Alnabru Skadesenter','skadeavdeling@oslo.toyota.no','KBreivollveien 27, 0668 Oslo',10.838935,59.923055);